### PR TITLE
changing the config to add Nepali language that is already localized 

### PR DESCRIPTION
**Pull request by sarojdhakal**

### CODE REVIEW

**Comment by eggpi** [comment]
Thank you! Can you please fix the errors in the Travis run?

Basically you're missing a `hidden_category` entry in the config, and you should use spaces instead of _ in `Citation_needed`.

By the way, is there a Nepali equivalent of `{{ Citation needed }}`, or do you just use the English template? If there are Nepali equivalents, you probably want to add those to the config too, please.

**Comment by eggpi** [comment]
Hi, would you still like to pursue this?

**Comment by sarojdhakal** [comment]
@eggpi Looks all good to me. Please let me know how can we have **ne** support in citation_hunt.

**Comment by eggpi** [comment]
Thanks, I'm setting this up now!

**Pull request merged**
