### PR TITLE
Use new WikiProject index tables

### PR DESCRIPTION
**Pull request by earwig**
We've changed the way the WikiProject index tables are laid out on the backend. The schema is a bit more complicated, but allows for much more flexibility—including better namespace and language support (though we're still limited to enwiki at the moment).

Anyway, I've updated the way you query the database here. It's nice because we can pull the page IDs directly in the initial query instead of making an individual SELECT for each page. As far as I can tell, this is the only place you use the project index tables. The new tables are ready to go as soon as you can merge this; the old tables will stay around for a little while longer in case something goes wrong. On that note, I haven't fully tested this (just the querying logic) so please let me know if something isn't right.

I realize PageAssessments is coming soon and will likely invalidate all of this, but until we reach that point...

### CODE REVIEW

**Comment by eggpi** [comment]
I think this looks good, let's merge this and we'll see if it causes trouble on the next database generation. Thanks!

**Comment by eggpi** [comment]
Oh, looks like this didn't quite work. The projects appear to be correctly loaded, but don't make it to the final set of categories. Maybe [this dict lookup](https://github.com/eggpi/citationhunt/blob/master/scripts/assign_categories.py#L224) is buggy somehow?

[Here's the logs from the latest databse generation](https://github.com/eggpi/citationhunt/files/379057/citationhunt_update_en.txt). I can investigate this some more later, but I've removed this commit from the server for now.

**Comment by earwig** [comment]
Strange. As you say, the logs indicate that the correct data is being fetched from our database, so the change there shouldn't have caused the problem. Looks like `pinned_categories_to_ids` is never being populated, so either `pinned_categories` is empty or `category_is_usable` is always returning False...

**Comment by earwig** [comment]
Looks like the page IDs in `unsourced_pageids` are strings, but our database returns ints. Judging by your last commit (faaa4df184a5f64173e61ed89c3d7f98b0649c9d), I guess you've already figured that out?

**Comment by eggpi** [comment]
Yep, just finished a database updated after faaa4df184a5f64173e61ed89c3d7f98b0649c9d, and WikiProjects are back, so looks like that was the problem. Thanks for looking :)

**Pull request merged**
