### PR TITLE
Get hidden categories from the page_props table

### PR DESCRIPTION
**Pull request by ricordisamoa**
Less need for manual configuration.

### CODE REVIEW

**Comment by ricordisamoa** [comment]
On enwiki, for example, there are 58 "hidden categories" according to `page_props` which are not actual categories (mostly templates), but only 1 "hidden category" according to `categorylinks` without `hiddencat` property ([diff](//en.wikipedia.org/w/index.php?title=Category:Wikipedia_articles_incorporating_text_from_the_United_States_Army_Institute_of_Heraldry&diff=653461631&oldid=530568970)).

**Comment by eggpi** [comment]
Looks great, thank you! One small thing though: since we now depend on `page_props` to generate the database locally, can you please update [the docs](https://github.com/eggpi/citationhunt/blob/master/scripts/README.md#generating-the-database-locally) accordingly? I always need to refer back to that when doing a new language.

**Comment by ricordisamoa** [comment]
Done. Now I feel guilty because of the new table requirement :disappointed:
Perhaps `hidden_category` could be inferred from the `hidden-category-category` message instead?

**Comment by eggpi** [comment]
Hmm, I can see [here](https://www.mediawiki.org/wiki/Help:Categories#Hidden_categories) that `hidden-category-category` contains that information, but how can we get to it? Is there an API call to retrieve system messages? Taking a step back, if `hidden-category-category` is always present in a wiki's config, then there will always exist a category name that we can manually put in our config, right?

I was hoping that, by using `page_props`, we would cover languages in which there is no category like that in `categorylinks`. But if there's always one, then yes, it's probably not worth it to change the current code if it adds dependencies. :confused:

**Comment by ricordisamoa** [comment]
Here it is: https://en.wikipedia.org/w/api.php?action=query&formatversion=2&meta=allmessages&ammessages=hidden-category-category&amlang=en

Tracking categories can be disabled (https://github.com/wikimedia/mediawiki/blob/26cf9f6ed9e722ec6ed34c9022e97b823ec51343/includes/parser/ParserOutput.php#L695) however that seems unlikely, at least on the largest Wikipedias.

**Comment by eggpi** [comment]
Very interesting! So, given that:

1. We are pretty sure we'll always have a category that we can refer to in the config
2. Your API example provides a very easy way to find out the name of that category from now on
3. Doing this programmatically will either have us depend on a new dump, or add an API query for what is essentially static information, to little gain overall

I think in this case it makes sense to just keep this configuration manual for now.

That being said, making the config process less manual in general is a great idea. For example, it would be really cool to have a script generate as much of the config as possible, including making the API call to get `hidden-category-category`. People could run this, fill in some blanks and make a PR to port to a new language.

Oh, and a config key that I'd very much like to get rid of is [`citation_needed_category`](https://github.com/eggpi/citationhunt/blob/master/config.py#L62), since I think it might not be as widespread as `hidden_category`. If you know of a way to get rid of that, it will likely be worth the extra dependence if we need it.

Anyway, sorry I kind of misunderstood the effects of this patch at first. Would you maybe be interested in working on one of the ideas above instead?

**Comment by ricordisamoa** [comment]
I'd like to automate the configuration step too, but I don't know the codebase enough to do much about it. Feel free to do anything with the PR. :hand:

**Comment by eggpi** [comment]
OK, I'm closing this now, but I'll definitely reuse the information here when automating the config. Thanks a lot for working on this!

**Comment by ricordisamoa** [comment]
Thank you!

**Pull request closed without merging**
