### PR TITLE
changed helper text for category filter

### PR DESCRIPTION
**Pull request by jessamynwest**
Showing this tool to people, a few found "What makes you tick?" confusing asking "What is that for?" and "what makes me tick?" Thought it might be better to change it to something more straightforward and less idiomatic.

### CODE REVIEW

**Comment by eggpi** [comment]
Thanks @jessamynwest! I'm happy to change this text to make it more obvious.

One question though: in your experience, are people usually aware that they can type in terms to search categories, or do they just try to select a category from the default options that appear after clicking the input box?

If the latter, I think switching to something like *Search categories* might help with that, too, and *Choose* may be a bit misleading. What do you think?

**Comment by jessamynwest** [comment]
A good point, maybe slightly different wording. I think when people see an alpha list they assume there's a long one. Maybe encourage typing?

"Start typing to select a category" 

might help and is more active language?

**Comment by eggpi** [comment]
Hmm, I like the idea of active language, but I'm a little concerned about sizes. [Text can grow](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_content_best_practices#Design_for_50) quite a bit when translated from English. For example, Google Translate says the Greek version would be:

> Ξεκινήστε να πληκτρολογείτε για να αναζητήσετε τις κατηγορίες

which awkwardly fills up most of the input box. Unfortunately we don't get line wrapping or scrolling in the input box, so text size can matter, and I'm not sure translators will know to account for that.

"Type to search categories" (or "Type to select a category") could work just as well though, and "Search categories" would also be fine I think. But if you can think of anything else around the same size as the current text, we can go with that too.

Sorry for the back-and-forth, I just want to make sure we won't regret this, which would waste translation effort :)

**Comment by jessamynwest** [comment]
I was wondering about that also. The simpler the better to my mind. No problem going back and forth on it. I agree it's better to get something that works well cross-culturally.

What about this?

"Search for a topic"

I think the fact that Wikipedia calls them categories problem doesn't matter so much for users of this tool and I think 'topic' may be more accessible than 'category' as a term.

**Comment by eggpi** [comment]
Sounds great! Please update the PR and I'll be happy to merge. Thank you!

**Comment by jessamynwest** [comment]
I think that's all done (I am sort of new to Github) so let me know if anything else needs to happen.

**Pull request merged**
