### PR TITLE
new language config - Croatian (hr)

### PR DESCRIPTION
**Pull request by Ivi104**
Hi! I edited the config.py file to allow support for hrwiki. I am unable to test my edits locally, but there shouldn't be any problems.

I already translated all the strings in TW.

### CODE REVIEW

**Comment by eggpi** [comment]
Looks like hr.json got merged into the repository today. Would you mind rebasing this on top of the master branch so we get one last test run before merging please?

**Comment by Ivi104** [comment]
First time rebasing, thank you Google. I hope everything is in order?

**Comment by eggpi** [comment]
Yes thank you! Let's merge and try this.

**Comment by eggpi** [comment]
Sorry this took a while, there was some breakage I needed to fix first. It should now be running at https://citationhunt.toolforge.org/hr. Thanks again for contributing this!

**Pull request merged**
